name: Node.js CI

on:
  push:
    branches: [ dev ]
    
defaults:
  run:
    working-directory: ./client
  

jobs:
  build:

    runs-on: [self-hosted,Linux,X64,frontend]

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        
    - name: Create Docker File
      run: node -v
    - name: LS CMD
      run: ls

      

