name: Node.js CI

on:
  push:
    branches: [ dev ]

jobs:
  build:

    runs-on: [self-hosted,Linux,X64,frontend]

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./client/package-lock.json
      
    - name: Create Docker File
      working-directory: ./client
      run: node -v


