name: Node.js CI / CD

on:
  push:
    branches: [ dev ]
    
defaults:
  run:
    working-directory: ./client
  

jobs:
  build:

    runs-on: [self-hosted,Linux,X64,frontend]

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: ./client/package-lock.json

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        context: ./client
        file: ./client/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/hr-portal:frontend
        
    - name: Create Fresh Frontend Service On Swarm 
      id: create
      run: docker service create --replicas 2 --publish published=4200,target=80 --name="frontendservice" yasiru1999/hr-portal:frontend
      continue-on-error: true
      
    - name: Update Frontend Service On Swarm 
      if: steps.create.outcome != 'success'
      run: docker service update --image yasiru1999/hr-portal:frontend frontendservice

      

